# 使用已有的EIP
apiVersion: game.kruise.io/v1alpha1
kind: GameServerSet
metadata:
  name: gs-eip-exist
  namespace: kruise-game-system
spec:
  replicas: 1
  updateStrategy:
    rollingUpdate:
      podUpdatePolicy: InPlaceIfPossible
  network:
    networkType: HwCloud-CCE-EIP
    networkConf:
      - name: yangtse.io/eip-id
        value: "120fc017-ad05-499c-9e3c-0c8585c8300b" # 使用已有的EIP
  gameServerTemplate:
    spec:
      containers:
#        - image: registry.cn-hangzhou.aliyuncs.com/gs-demo/gameserver:network
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: nginx-html
              mountPath: /usr/share/nginx/html
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh", "-c", "echo \"<html><body><h1>Welcome to $POD_NAME</h1></body></html>\" > /usr/share/nginx/html/index.html" ]
      volumes:
        - name: nginx-html
          emptyDir: { }