apiVersion: v1
kind: Service
metadata:
  annotations:
#    kubernetes.io/elb.class: performance
    kubernetes.io/elb.class: union
    kubernetes.io/elb.autocreate: '{
      "type": "public",
      "bandwidth_name": "bandwidth-89f0",
      "bandwidth_chargemode": "traffic",
      "bandwidth_size": 5,
      "bandwidth_sharetype": "PER",
      "eip_type": "5_bgp",
      "available_zone": [
         "ap-southeast-1a",
         "ap-southeast-1b"
      ],
      "l4_flavor_name": "L4_flavor.elb.s1.small"
    }'
    kubernetes.io/elb.enterpriseID: 'aff97261-4dbd-4593-8236-d7a5daf6a943'
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
  labels:
    statefulset.kubernetes.io/pod-name: gs-elb-performance-0
  name: nginx-autocreate
  namespace: kruise-game-system
spec:
  ports:
    - name: service0
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    statefulset.kubernetes.io/pod-name: gs-elb-performance-0
  type: LoadBalancer