apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dynamic
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: nginx-html
              mountPath: /usr/share/nginx/html
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "echo \"<html><body><h1>Welcome to $POD_NAME</h1></body></html>\" > /usr/share/nginx/html/index.html"]
      volumes:
        - name: nginx-html
          emptyDir: {}